name: Aspnetapp1 Scan Docker Images
on:
  push:
    branches: [ main ]
    paths:
      - 'src/aspnetapp1/**'
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  security-events: write
  contents: read
  actions: read    
jobs:
  call-docker-scan:
    # Points to your reusable workflow file path
    uses: ./.github/workflows/reusable_scan.yml
    with:
      context: .
      dockerfile_path: src/aspnetapp/Dockerfile
      image_name: venukulk/aspnetapp
    secrets: inherit
